### ISSUE TITLE
ginkgo: command not found

### ISSUE THREAD

**Issue by EricForgy** [ava-labs/indexvm#17]
Trying to run with
```
./scripts/tests.load.sh
```
I get
```
./scripts/tests.load.sh: line 24: ginkgo: command not found
```

I'm pretty sure the solution will be to install ginkgo, but just FYI.

**Comment by patrick-ogrady** [comment]
Did some research and I actually do attempt to install `ginkgo` if it doesn't exist:
```bash
go install -v github.com/onsi/ginkgo/v2/ginkgo@v2.1.4
```

Did you remove this line?

**Comment by EricForgy** [comment]
I did not remove anything. I just cloned the repo and tried 
```
./scripts/run.sh
```
🤔

**Comment by patrick-ogrady** [comment]
https://github.com/ava-labs/hypersdk/issues/37#issuecomment-1444609854
